In [9]:
import numpy as np
import random

#creating a random vector of size 15 having only integers from 1 to 20
rand_vector = np.random.randint(low=1,high=21,size=15)
print(rand_vector)

# Reshaping the array to 3 by 5
array1 = rand_vector.reshape(3,5)
print(array1)

# Print the shape of the array
print("The shape of the array is:" , array1.shape)

# Replace the max in each row by 0

# Finding the max indexes in each row
max_indexes = np.argmax(array1 , axis=1)
i=0
# iterating over the max indexes
for j in max_indexes:
     array1[i][j]=0
     i += 1
print("updated array1:\n" , array1)

# creating a 2d array of 4 by 3
array2 = np.array(np.random.randint(1 , 21, size=(4,3)), np.int32)
# Printing array shape
print("Shape:", array2.shape)
# Printing array type
print("type:", type(array2))
#printing array datatype
print("data type:", array2.dtype)






[ 8 10 15 20  1 12  5 17  3 18  3 14 11  5 15]
[[ 8 10 15 20  1]
 [12  5 17  3 18]
 [ 3 14 11  5 15]]
The shape of the array is: (3, 5)
updated array1:
 [[ 8 10 15  0  1]
 [12  5 17  3  0]
 [ 3 14 11  5  0]]
Shape: (4, 3)
type: <class 'numpy.ndarray'>
data type: int32


In [11]:
# Defining the given array
array3 = np.array([[3 , -2] , [1 , 0]])
# Computing the eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(array3)
# Printing eigenvalues
print("eigenvalues:\n", eigenvalues)
# printing right eigenvectors
print("\nRight eigenvectors:\n" , eigenvectors )

eigenvalues:
 [2. 1.]

Right eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [12]:
# Defining the given array
array4 = np.array([[0, 1, 2],[3, 4, 5]])
# Computing the sum of the diagonal elements
sum_diagonal = np.trace(array4)
sum_diagonal

4

In [20]:
# Defining the given array
array5 = np.array([[1, 2],[3, 4],[5, 6]])
# Reshaping the array to 2 by 3 without changing the data
new_array5 = array5.reshape(2, 3)
print("new array5:",new_array5)

# Defining another array
array6 = np.array([[1, 2, 3], [4, 5, 6]])
# Reshaping the array to 3 by 2
new_array6 = array6.reshape(3, 2)
print("new array6:\n",new_array6)


new array5: [[1 2 3]
 [4 5 6]]
new array6:
 [[1 2]
 [3 4]
 [5 6]]
